# Generated by Django 2.1.2 on 2018-10-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('parentContactNumber', models.CharField(max_length=10, verbose_name="Parent's Contact Number")),
                ('address', models.TextField()),
                ('height', models.CharField(max_length=100, verbose_name='Height (CM)')),
                ('weight', models.CharField(max_length=100, verbose_name='Weight (KG)')),
                ('about', models.TextField(blank=True, null=True)),
                ('vector_encoding', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
