# Generated by Django 2.1.2 on 2018-10-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='vector_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
