# Generated by Django 2.1.2 on 2018-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181014_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='about',
        ),
        migrations.AddField(
            model_name='person',
            name='complexion',
            field=models.CharField(default='Fair', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='fathersName',
            field=models.CharField(default='Rahul', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='nearest_police_station',
            field=models.CharField(default='Ramesh Nagar', max_length=100),
            preserve_default=False,
        ),
    ]
